### ISSUE TITLE
Deprecated align, but no other way for using it?

### ISSUE THREAD

**Issue by Chrissyx** [intive-FDV/DynamicJasper#103]
The `VerticalAlign` and `HorizontalAlign` have been marked as deprecated:

https://github.com/intive-FDV/DynamicJasper/blob/master/src/main/java/ar/com/fdvs/dj/domain/Style.java#L83

However, there is no way to set the new Text and Image alternatives? Same for the `StyleBuilder`:

https://github.com/intive-FDV/DynamicJasper/blob/master/src/main/java/ar/com/fdvs/dj/domain/builders/StyleBuilder.java#L100

Did I miss something or is this a bug?

**Comment by jonathanbenedet** [comment]
Same problem here.

**Comment by AnomalyAces** [comment]
I want to say I have seen the same thing. It supports the deprecated code but I think we should either have a way to set the new Text and Image aligns or the deprecation marker should be removed

**Comment by sandeepnkulkarni** [comment]
I am facing same problem. Any update on this would be appreciated.
