### ISSUE TITLE
Chinese font issues of  running  on k8s

### ISSUE THREAD

**Issue by YongMingMao** [intive-FDV/DynamicJasper#116]
I had add Chinese font  into DynamicJasper-core-fonts project
and the application runs well and able to display Chinese characters.

but when I deploy the application on k8s, it only can display part of Chinese characters.
`
DJChartBuilder cb1 = new DJChartBuilder();
            DJChartBuilder chart =  cb1.setType(DJChart.BAR_CHART)
                    .setOperation(DjFooterVariableOperationFactory.getFooterVariableOperation(groupMeta.getChartOperation()).getValue())
                    .setPosition(DJChartOptions.POSITION_HEADER)
                    .setShowLabels(true);
            chart = buildChart(chart, groupMeta, chartMeta.getColumnMetaList(), columns, djGroups);
            chart = chart.setHeight(CHART_HEIGHT);
            builder = builder.addChart(chart.build());
`
thanks

**Comment by juanalvarezg** [comment]
try using core-fonts 2.1
