### ISSUE TITLE
Remove use of commons collections 3

### ISSUE THREAD

**Issue by sandeepnkulkarni** [intive-FDV/DynamicJasper#123]
commons collections 3 is EOL and there is no new version available since Nov, 2015 after 3.2.2. So it would make sense to remove its use within DynamicJasper going forward. Our customers have shown concern about its continued use and hence the request.

I have gone through the source code of DynamicJasper and it is used only within class AbstractLayoutManager and no where else. It is really easy to convert the code to use commons collections 4. Rest of the places already use classes from commons collections 4.

Earlier jasperreports was also using commons collections 3, but since 6.11.0 there have also removed its use. So we can specify a higher minimum version to 6.11.0 so that commons collections 3 is not added as a transitive dependency.

Last place where commons collections 3 is used is by commons-beanutils 1.9.4. There is major version of beanutils released commons-beanutils2 which no longer needs commons collections 3 and uses commons collections 4 in its place. But I also found that DynamicJasper is not using any functionality from beanutils at all. As per my understanding it is coming via JasperReports Library. So it can be safely removed.

Please correct me if I am wrong in above assessment.

**Comment by sandeepk-veritas** [comment]
Any comments would be appreciated.
