### ISSUE TITLE
NoSuchMethodError with jasperreport 6.19.0

### ISSUE THREAD

**Issue by jherkel** [intive-FDV/DynamicJasper#124]
with a new jasperreport 6.19.0 I can see this exception:
```
java.lang.NoSuchMethodError: 'void net.sf.jasperreports.engine.JRPen.setLineWidth(float)'
	at ar.com.fdvs.dj.util.LayoutUtils.convertBorderToPen(LayoutUtils.java:186) ~[DynamicJasper-5.3.3.jar:?]
```
I have checked changes between 6.18.0 & 6.19.0 and there was removed a deprecated method 
```
/**
 * @deprecated Replaced by {@link #setLineWidth(Float)}.
 */
public void setLineWidth(float lineWidth);

```

**Comment by objt-ev** [comment]
having same issue, this prevents us from migrating to the latest jasper reports (6.18.1+)

**Comment by oyarzun** [comment]
@juanalvarezg any thoughts on merging @jherkel 's PR #129 to fix this issue?
