### ISSUE TITLE
dynamicjasper website is down.

### ISSUE THREAD

**Issue by svkirans** [intive-FDV/DynamicJasper#143]
https://dynamicjasper.com/ is no longer accessible.

**Comment by richie-chauhan** [comment]
Still down. Please help.

**Comment by oyarzun** [comment]
Looks like was moved to use GitHub Pages. http://intive-fdv.github.io/DynamicJasper/

@juanalvarezg correct me if I am wrong.

**Comment by juanalvarezg** [comment]
Correct, I'm still migrating some pages, but the main content is already there.
