### ISSUE TITLE
orientation lost during DJJRDesignHelper.downCast

### ISSUE THREAD

**Issue by seboss69** [intive-FDV/DynamicJasper#79]
Hello, during the DJJRDesignHelper.downCast function, the DynamicJasperDesign returned doesn't copy the orientation.

It causes trouble when you want to print the generated report, it doesn't automatically select the landscape orientation for example.

Here is the example (i can't upload .java and .jrxml you must rename it !)

[landscape2.txt](https://github.com/intive-FDV/DynamicJasper/files/2957438/landscape2.txt)

[DJOrientationIssue.txt](https://github.com/intive-FDV/DynamicJasper/files/2957433/DJOrientationIssue.txt)

By adding the instruction 

> djd.setOrientation(jd.getOrientationValue());

In the downCast function, the problem doesn't appear anymore.

**Comment by juanalvarezg** [comment]
I need to add this...
