### ISSUE TITLE
Can't Remove INFO logs

### ISSUE THREAD

**Issue by joethejones** [intive-FDV/DynamicJasper#82]
plsplsplsplsplspslspls, can someone inform me how to remove INFO logs from DynamicJasper.

I love this tool, but am sick of trying to deal with all of the info logs. 

I also can't just switch ALL info logs off, as I need them!

Is there a way to just switch them off in this tool? Does anyone knpw

Manythanks

**Comment by juanalvarezg** [comment]
In your logs, just set this category: "ar.com.fdvs.dj" into ERROR only, that should do the trick.
