### ISSUE TITLE
Latest Dynamic Jasper and Jasper Reports 6.9.0 compatibility

### ISSUE THREAD

**Issue by shustinho** [intive-FDV/DynamicJasper#85]
Hello,
Just upgraded Jasper Reports to the latest version (6.9.0)
As a result report generation made on DJ 5.1.2 starts failing. 
Method not found Exception is thrown here:
JRBaseStyle.setHorizontalAlignment .

How this can be fixed or when compatible version of DJ will be released?

**Comment by tkofford** [comment]
I'm also having this issue. When will DJ support Jasper Reports 6.9.0-6.10.0?

**Comment by LisaKabra** [comment]
Hello , 
I am totally new to dynamic jaspers , wanted to know can i switch to dynamic jasper from dynamic reports ?
or should i use jasper reports directly ?

**Comment by maksimu** [comment]
Getting error using `DynamicJasper:5.1.2` and `JapserReports:6.11.0` running `FastReportTest` report

**Comment by juanalvarezg** [comment]
Hello everyone, just released DJ 5.3.0 that supports JR 6.8+
