### ISSUE TITLE
Subtract Two FooterVariable and add the sum in next FooterVariable.

### ISSUE THREAD

**Issue by knaven0128** [intive-FDV/DynamicJasper#89]
![Screen Shot 2020-02-14 at 5 09 56 PM](https://user-images.githubusercontent.com/30900072/74518338-9be8f380-4f4e-11ea-90cb-931ae70dfa3f.png)

For example in this image i want to subtract the sum of credit and debit and add the sum next to the credit sum inline. and i want to do it DJGRoup. Thanks

**Comment by juanalvarezg** [comment]
Sorry, no such thing
